load("@rules_cc//cc:cc_binary.bzl", "cc_binary")

# Common utilities library

filegroup(
    name = "inputs",
    srcs = glob(["input*.txt"]),
)

cc_binary(
    name = "day1",
    srcs = ["day1.cc"],
    data = [":inputs"],
    deps = [
        "//utils:common",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
    ],
)
cc_binary(
    name = "day2",
    srcs = ["day2.cc"],
    data = [":inputs"],
    deps = [
        "//utils:common",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
    ],
)

cc_binary(
    name = "day3",
    srcs = ["day3.cc"],
    data = [":inputs"],
    deps = [
        "//utils:common",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
    ],
)
cc_binary(
    name = "day4",
    srcs = ["day4.cc"],
    data = [":inputs"],
    deps = [
        "//utils:common",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
    ],
)

cc_binary(
    name = "day5",
    srcs = ["day5.cc"],
    data = [":inputs"],
    deps = [
        "//utils:common",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
    ],
)

cc_binary(
    name = "day6",
    srcs = ["day6.cc"],
    data = [":inputs"],
    deps = [
        "//utils:common",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
    ],
)

cc_binary(
    name = "day7",
    srcs = ["day7.cc"],
    data = [":inputs"],
    deps = [
        "//utils:common",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
    ],
)

cc_binary(
    name = "day8",
    srcs = ["day8.cc"],
    data = [":inputs"],
    deps = [
        "//utils:common",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
    ],
)

cc_binary(
    name = "day9",
    srcs = ["day9.cc"],
    data = [":inputs"],
    deps = [
        "//utils:common",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
    ],
)

