#!/bin/bash

YEAR=$1
DAY=$2

touch "$YEAR/day${DAY}.cc"
touch "$YEAR/input${DAY}.txt"
touch "$YEAR/input${DAY}_full.txt"

cat >> "$YEAR/BUILD" << EOL
cc_binary(
    name = "day${DAY}",
    srcs = ["day${DAY}.cc"],
    data = [":inputs"],
    deps = [
        "//utils:common",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
    ],
)

EOL

cat >> "$YEAR/day${DAY}.cc" << EOL
// from https://adventofcode.com/${YEAR}/day/${DAY}

#include <fstream>
#include <iostream>
#include <filesystem>

#include "absl/status/status.h"
#include "absl/strings/numbers.h"

#include "utils/common.h"

using namespace std;
using namespace aoc;
namespace fs = std::filesystem;

// std::string kInputFname = "${YEAR}/input${DAY}.txt";
string kInputFname = "${YEAR}/input${DAY}_full.txt";

absl::Status ReadInput(const string input_filename) {

    RETURNERRORIF(
        !fs::exists(input_filename),
        absl::StatusCode::kNotFound,
        "input file doesnt exists");
    ifstream file(input_filename);
    string line;
    while (getline(file, line)) {}
    return absl::OkStatus();
}

void part1() {}
void part2() {}

int main()
{
    auto res = ReadInput(kInputFname);
    if (!res.ok())
    {
        cout << "error reading input: " << res << endl;
        return 1;
    }
    part1();
    part2();
    return 0;
}

EOL
