load("@rules_python//python:defs.bzl", "py_binary")

# Day 1 binary
py_binary(
    name = "day1",
    srcs = ["day1.py"],
    data = [
        "day1_input.txt",
        "day1_input_test.txt",
    ],
)

# Day 2 binary
py_binary(
    name = "day2",
    srcs = ["day2.py"],
    data = [
        "day2_input.txt",
        "day2_input_test.txt",
    ],
)

# Day 3 binary
py_binary(
    name = "day3",
    srcs = ["day3.py"],
    data = [
        "day3_input.txt",
        "day3_input_test.txt",
    ],
)

# Day 4 binary
py_binary(
    name = "day4",
    srcs = ["day4.py"],
    data = [
        "day4_input.txt",
        "day4_input_test.txt",
    ],
)

# Day 5 binary
py_binary(
    name = "day5",
    srcs = ["day5.py"],
    data = [
        "day5_input.txt",
        "day5_input_test.txt",
        "day5_input_test_2.txt",
    ],
)

# Day 6 binary
py_binary(
    name = "day6",
    srcs = ["day6.py"],
    data = [
        "day6_input.txt",
        "day6_input_test.txt",
    ],
)

# Day 7 binary
py_binary(
    name = "day7",
    srcs = ["day7.py"],
    data = [
        "day7_input.txt",
        "day7_input_test.txt",
    ],
)

# Day 8 binary
py_binary(
    name = "day8",
    srcs = ["day8.py"],
    data = [
        "day8_input.txt",
        "day8_input_test.txt",
        "day8_input_test_short.txt",
    ],
)

# Day 9 binary
py_binary(
    name = "day9",
    srcs = ["day9.py"],
    data = [
        "day9_input.txt",
        "day9_input_test.txt",
    ],
)

# Day 10 binary
py_binary(
    name = "day10",
    srcs = ["day10.py"],
    data = [
        "day10_input.txt",
        "day10_input_test.txt",
    ],
)
